- .github/workflows/deploy-dev.yml
- .github/workflows/deploy-prod.yml
- .gitignore
- deploy/dev/deploy.sh
- deploy/nginx.conf
- deploy/prod/deploy.sh
- src/main/resources/application-dev.yml
- src/main/resources/application-prod.yml
- src/main/resources/local-db.yml
> develop 브랜치에 ci/cd 적용 + slack 연동

- src/main/java/com/devnity/devnity/domain/admin/controller/AdminCourseController.java
- src/main/java/com/devnity/devnity/domain/admin/controller/dto/CourseRequestDto.java
- src/main/java/com/devnity/devnity/domain/admin/controller/dto/CourseResponseDto.java
- src/main/java/com/devnity/devnity/domain/admin/repository/CourseRepository.java
- src/main/java/com/devnity/devnity/domain/admin/service/AdminCourseService.java
- src/main/java/com/devnity/devnity/domain/user/entity/Course.java
- src/test/java/com/devnity/devnity/domain/admin/controller/AdminCourseControllerTest.java
- #35 
<br>
- 코스 API 구현
<br>
<br>
- Exception PR 머지 후 Business Exception 으로 변경 필요
<br>
3h
<br>
> [Admin-35] 코스 API 구현

- src/main/java/com/devnity/devnity/common/error/ErrorResponse.java
- #39 
<br>
ErrorResponse클래스 serverDatetime(서버시간) 추가
<br>
<br>
탭간격 4 -> 2로 코드 reformat함
<br>
5m
<br>
> [Common-39] ErrorResponse클래스 서버시간 추가

- src/main/java/com/devnity/devnity/common/config/JpaAuditingConfig.java
- src/main/java/com/devnity/devnity/common/config/SpringSecurityAuditorAware.java
- src/main/java/com/devnity/devnity/common/entity/BaseEntity.java
- src/main/java/com/devnity/devnity/common/error/ErrorResponse.java
- src/main/java/com/devnity/devnity/common/error/GlobalExceptionHandler.java
- src/main/java/com/devnity/devnity/common/error/exception/BusinessException.java
- src/main/java/com/devnity/devnity/common/error/exception/EntityNotFoundException.java
- src/main/java/com/devnity/devnity/common/error/exception/ErrorCode.java
- src/main/java/com/devnity/devnity/common/error/exception/InvalidValueException.java
- src/main/java/com/devnity/devnity/common/response/ApiResponse.java
- src/test/java/com/devnity/devnity/common/entity/BaseEntityTest.java
- #38 
<br>
BaseEntity구현
ApiResponse구현
<br>
<br>
<br>
2h
<br>
> [Common-38] ApiResponse, BaseEntity 구현

- src/main/java/com/devnity/devnity/domain/auth/jwt/JwtAuthenticationProvider.java
- src/main/java/com/devnity/devnity/domain/auth/service/AuthService.java
- src/main/java/com/devnity/devnity/domain/user/controller/UserController.java
- src/main/java/com/devnity/devnity/domain/user/dto/request/SignUpRequest.java
- src/main/java/com/devnity/devnity/domain/user/repository/CourseRepository.java
- src/main/java/com/devnity/devnity/domain/user/repository/GenerationRepository.java
- src/main/java/com/devnity/devnity/domain/user/repository/GroupRepository.java
- src/main/java/com/devnity/devnity/domain/user/repository/UserRepository.java
- src/main/java/com/devnity/devnity/domain/user/service/UserService.java
- src/main/java/com/devnity/devnity/domain/user/service/UserServiceUtils.java
- src/main/resources/data.sql
- src/main/resources/truncate-data.sql
- src/test/java/com/devnity/devnity/domain/auth/controller/AuthControllerTest.java
- src/test/java/com/devnity/devnity/domain/user/controller/UserControllerTest.java
- src/test/java/com/devnity/devnity/domain/user/repository/CourseRepositoryTest.java
- src/test/java/com/devnity/devnity/domain/user/repository/GenerationRepositoryTest.java
- src/test/java/com/devnity/devnity/domain/user/repository/GroupRepositoryTest.java
- src/test/java/com/devnity/devnity/domain/user/repository/UserRepositoryTest.java
- src/test/java/com/devnity/devnity/domain/user/service/UserServiceTest.java
- issue: #22 
<br>
회원 가입 기능 구현
<br>
<br>
<br>
3h
<br>
> [User-22] 회원 가입 기능 구현

- src/docs/asciidoc/domain/users.adoc
- src/main/java/com/devnity/devnity/common/config/WebMvcConfig.java
- src/main/java/com/devnity/devnity/common/config/WebSecurityConfig.java
- src/main/java/com/devnity/devnity/domain/auth/controller/AuthController.java
- src/main/java/com/devnity/devnity/domain/auth/jwt/JwtAuthenticationFilter.java
- src/main/java/com/devnity/devnity/domain/user/controller/UserController.java
- src/test/java/com/devnity/devnity/domain/auth/controller/AuthControllerTest.java
- src/test/java/com/devnity/devnity/domain/user/controller/UserControllerTest.java
- issue: #48 
<br>
피드백 반영, CORS 설정
<br>
<br>
<br>
1H
<br>
> [User-48] 피드백 반영 & CORS 설정

- src/main/java/com/devnity/devnity/common/config/SchedulerConfig.java
- #50
<br>
SchedulerConfig 추가
<br>
<br>
<br>
5m
<br>
> [Common-50] SchedulerConfig 추가

- src/main/java/com/devnity/devnity/domain/mapgakco/entity/Mapgakco.java
- src/main/java/com/devnity/devnity/domain/mapgakco/entity/MapgakcoApplicant.java
- src/main/java/com/devnity/devnity/domain/mapgakco/entity/MapgakcoComment.java
- src/main/java/com/devnity/devnity/domain/mapgakco/entity/MapgakcoCommentStatus.java
- src/main/java/com/devnity/devnity/domain/mapgakco/entity/MapgakcoStatus.java
- #53 
<br>
Mapgakco 도메인 BaseEntity 상속
<br>
<br>
<br>
<br>
> [Common-53] Mapgakco 도메인 BaseEntity 상속

- src/main/java/com/devnity/devnity/domain/mapgakco/controller/MapgakcoApplicantV1Controller.java
- src/main/java/com/devnity/devnity/domain/mapgakco/controller/MapgakcoCommnetV1Controller.java
- src/main/java/com/devnity/devnity/domain/mapgakco/controller/MapgakcoController.java
- src/main/java/com/devnity/devnity/domain/mapgakco/controller/MapgakcoV1Controller.java
- src/main/java/com/devnity/devnity/domain/mapgakco/dto/mapgakco/MapgakcoCreateRequest.java
- src/main/java/com/devnity/devnity/domain/mapgakco/dto/mapgakcocomment/MapgakcoCommentCreateRequest.java
- src/main/java/com/devnity/devnity/domain/mapgakco/entity/Mapgakco.java
- src/main/java/com/devnity/devnity/domain/mapgakco/entity/MapgakcoApplicant.java
- src/main/java/com/devnity/devnity/domain/mapgakco/entity/MapgakcoComment.java
- src/main/java/com/devnity/devnity/domain/mapgakco/repository/MapgakcoApplicantRepository.java
- src/main/java/com/devnity/devnity/domain/mapgakco/repository/MapgakcoCommentRepository.java
- src/main/java/com/devnity/devnity/domain/mapgakco/service/MapgakcoApplicantService.java
- src/main/java/com/devnity/devnity/domain/mapgakco/service/MapgakcoCommentService.java
- src/main/java/com/devnity/devnity/domain/mapgakco/service/MapgakcoService.java
- #56 
<br>
Mapgakco domain 재정의
#56 참고
<br>
<br>
<br>
20m
<br>
> [Mapgakco-56] Mapgakco domain 재정의

- src/main/java/com/devnity/devnity/common/config/WebSecurityConfig.java
- src/main/java/com/devnity/devnity/domain/auth/controller/AuthController.java
- src/main/java/com/devnity/devnity/domain/introduction/dto/IntroductionDto.java
- src/main/java/com/devnity/devnity/domain/introduction/entity/Introduction.java
- src/main/java/com/devnity/devnity/domain/introduction/respository/IntroductionRepository.java
- src/main/java/com/devnity/devnity/domain/user/controller/UserController.java
- src/main/java/com/devnity/devnity/domain/user/dto/SimpleUserInfoDto.java
- src/main/java/com/devnity/devnity/domain/user/dto/UserDto.java
- src/main/java/com/devnity/devnity/domain/user/dto/response/UserInfoResponse.java
- src/main/java/com/devnity/devnity/domain/user/entity/User.java
- src/main/java/com/devnity/devnity/domain/user/repository/CourseRepository.java
- src/main/java/com/devnity/devnity/domain/user/service/UserService.java
- src/test/java/com/devnity/devnity/domain/introduction/respository/IntroductionRepositoryTest.java
- src/test/java/com/devnity/devnity/domain/introduction/service/IntroductionServiceTest.java
- src/test/java/com/devnity/devnity/domain/user/controller/UserControllerTest.java
- src/test/java/com/devnity/devnity/domain/user/service/UserServiceTest.java
- src/test/java/com/devnity/devnity/test/annotation/WithJwtAuthUser.java
- src/test/java/com/devnity/devnity/test/config/WithJwtAuthUserSecurityContext.java
-issue: #25 
<br>
- 내 정보 조회 기능(자기소개까지)
<br>
- 피드백 반영하였음 (#24)
<br>
<br>
2h
<br>
> [User-25] 내 정보 조회

- src/main/java/com/devnity/devnity/common/api/CursorPageRequest.java
- src/main/java/com/devnity/devnity/common/api/CursorPageResponse.java
- #31 
<br>
고민 많이 했는데 별거 없어서 머쓱하네요 😅
일단은 id정렬만 이용하여 request에서는 lastId와 페이징 size를,
response에서는 페이징 내용이 들어갈 values를 제외하고 5가지 필드를 추가해 뒀습니다.
그 내용은 CursorPageResponse에 주석으로 적어뒀습니다.
<br>
<br>
<br>
1h
<br>
> [Common-31] CursorPageRequest, CursorPageResponse 추가

- src/docs/asciidoc/domain/admin.adoc
- src/main/java/com/devnity/devnity/domain/admin/controller/AdminCourseController.java
- src/main/java/com/devnity/devnity/domain/admin/controller/dto/CourseRequest.java
- src/main/java/com/devnity/devnity/domain/admin/controller/dto/CourseResponse.java
- src/main/java/com/devnity/devnity/domain/admin/service/AdminCourseService.java
- src/test/java/com/devnity/devnity/domain/admin/controller/AdminCourseControllerTest.java
- #35 
<br>
- #37 피드백 반영
<br>
- ApiResponse 사용
- BusinessException 으로 변경
- RestDocs 설정
- 코스 수정 URI 변경
<br>
<br>
<br>
> [Admin-35] 코스 API PR 피드백 반영

- src/main/java/com/devnity/devnity/common/error/GlobalExceptionHandler.java
- src/main/java/com/devnity/devnity/common/error/exception/EntityNotFoundException.java
- #86 
<br>
EntityNotFoundException, GlobalExceptionHandler 수정
<br>
<br>
<br>
5m
<br>
> [Common-86] EntityNotFoundException, GlobalExceptionHandler 수정

- src/main/java/com/devnity/devnity/common/error/exception/ErrorCode.java
- src/main/java/com/devnity/devnity/domain/mapgakco/controller/MapgakcoV1Controller.java
- src/main/java/com/devnity/devnity/domain/mapgakco/service/MapgakcoService.java
- src/test/java/com/devnity/devnity/domain/mapgakco/controller/MapgakcoV1ControllerTest.java
- src/test/java/com/devnity/devnity/domain/mapgakco/service/MapgakcoServiceTest.java
- #79 
<br>
맵각코 삭제 API 구현
삭제 비즈니스 로직 Test
<br>
ErrorCode 추가했습니다.
<br>
<br>
1h
<br>
> [Mapgakco-79] 맵각코 삭제 API 구현

- src/main/java/com/devnity/devnity/domain/gather/dto/request/CreateGatherCommentRequest.java
- src/main/java/com/devnity/devnity/domain/gather/dto/request/CreateGatherRequest.java
- src/main/java/com/devnity/devnity/domain/introduction/controller/IntroductionLikeController.java
- src/main/java/com/devnity/devnity/domain/introduction/exception/IntroductionLIkeDuplicateException.java
- src/main/java/com/devnity/devnity/domain/introduction/exception/IntroductionLikeNotFoundException.java
- src/main/java/com/devnity/devnity/domain/introduction/respository/IntroductionLikeRepository.java
- src/main/java/com/devnity/devnity/domain/introduction/service/IntroductionLikeService.java
- src/main/java/com/devnity/devnity/domain/introduction/service/IntroductionService.java
- src/main/java/com/devnity/devnity/domain/user/utils/validator/PasswordValidator.java
- src/test/java/com/devnity/devnity/domain/introduction/controller/IntroductionLikeControllerTest.java
- src/test/java/com/devnity/devnity/domain/introduction/respository/IntroductionLikeRepositoryTest.java
- src/test/java/com/devnity/devnity/domain/introduction/service/IntroductionLikeServiceTest.java
- src/test/java/com/devnity/devnity/domain/user/dto/request/SignUpRequestTest.java
- src/test/java/com/devnity/devnity/setting/annotation/WithJwtAuthUser.java
- #73 
<br>
- 자기소개 좋아요 기능 구현
<br>
<br>
- 모집 기능에서 테스트 오류가 나는데 dto에 기본 생성자가 없어서 발생해서 제가 직접 추가 했습니다.
<br>
3H
<br>
> [User-73] 자기소개 좋아요 기능 구현

- src/main/java/com/devnity/devnity/domain/gather/dto/request/CreateGatherCommentRequest.java
- src/main/java/com/devnity/devnity/domain/gather/dto/request/CreateGatherRequest.java
- src/main/java/com/devnity/devnity/domain/introduction/controller/IntroductionCommentController.java
- src/main/java/com/devnity/devnity/domain/introduction/controller/IntroductionLikeController.java
- src/main/java/com/devnity/devnity/domain/introduction/dto/request/SaveIntroductionCommentRequest.java
- src/main/java/com/devnity/devnity/domain/introduction/dto/response/SaveIntroductionCommentResponse.java
- src/main/java/com/devnity/devnity/domain/introduction/entity/IntroductionComment.java
- src/main/java/com/devnity/devnity/domain/introduction/exception/IntroductionCommentNotFoundException.java
- src/main/java/com/devnity/devnity/domain/introduction/exception/IntroductionLIkeDuplicateException.java
- src/main/java/com/devnity/devnity/domain/introduction/exception/IntroductionLikeNotFoundException.java
- src/main/java/com/devnity/devnity/domain/introduction/exception/InvalidParentCommentException.java
- src/main/java/com/devnity/devnity/domain/introduction/respository/IntroductionCommentRepository.java
- src/main/java/com/devnity/devnity/domain/introduction/respository/IntroductionLikeRepository.java
- src/main/java/com/devnity/devnity/domain/introduction/service/IntroductionCommentService.java
- src/main/java/com/devnity/devnity/domain/introduction/service/IntroductionLikeService.java
- src/main/java/com/devnity/devnity/domain/introduction/service/IntroductionService.java
- src/main/java/com/devnity/devnity/domain/user/utils/validator/PasswordValidator.java
- src/test/java/com/devnity/devnity/domain/introduction/controller/IntroductionCommentControllerTest.java
- src/test/java/com/devnity/devnity/domain/introduction/controller/IntroductionControllerTest.java
- src/test/java/com/devnity/devnity/domain/introduction/controller/IntroductionLikeControllerTest.java
- src/test/java/com/devnity/devnity/domain/introduction/dto/request/SaveIntroductionCommentRequestTest.java
- src/test/java/com/devnity/devnity/domain/introduction/entity/IntroductionCommentTest.java
- src/test/java/com/devnity/devnity/domain/introduction/respository/IntroductionLikeRepositoryTest.java
- src/test/java/com/devnity/devnity/domain/introduction/service/IntroductionCommentServiceTest.java
- src/test/java/com/devnity/devnity/domain/introduction/service/IntroductionLikeServiceTest.java
- src/test/java/com/devnity/devnity/domain/user/dto/request/SignUpRequestTest.java
- src/test/java/com/devnity/devnity/setting/annotation/WithJwtAuthUser.java
- src/test/java/com/devnity/devnity/setting/provider/TestHelper.java
- close: #71 
<br>
데둥이 소개 댓글 생성 기능을 구현했습니다.
<br>
<br>
- 대댓글 기능 깊이 테스트에 유의 해야 할 것 같습니다!
<br>
3H
<br>
> [User-71] 데둥이 소개 댓글 & 대댓글 생성 기능 구현

- src/main/java/com/devnity/devnity/common/error/exception/ErrorCode.java
- src/main/java/com/devnity/devnity/domain/mapgakco/controller/MapgakcoApplicantV1Controller.java
- src/main/java/com/devnity/devnity/domain/mapgakco/controller/MapgakcoV1Controller.java
- src/main/java/com/devnity/devnity/domain/mapgakco/entity/Mapgakco.java
- src/main/java/com/devnity/devnity/domain/mapgakco/repository/MapgakcoApplicantRepository.java
- src/main/java/com/devnity/devnity/domain/mapgakco/service/mapgakcoapplicant/MapgakcoApplicantService.java
- src/test/java/com/devnity/devnity/domain/mapgakco/service/mapgakcoapplicant/MapgakcoApplicantQueryMethodTest.java
- src/test/java/com/devnity/devnity/domain/mapgakco/service/mapgakcoapplicant/MapgakcoApplicantServiceTest.java
- #75 
<br>
<br>
에러코드 추가
<br>
<br>
1h 30m
<br>
> [Mapgakco-75] 맵각코 신청 취소 API 구현

- src/main/java/com/devnity/devnity/common/api/CursorPageRequest.java
- src/main/java/com/devnity/devnity/domain/introduction/controller/IntroductionController.java
- src/main/java/com/devnity/devnity/domain/introduction/dto/IntroductionDto.java
- src/main/java/com/devnity/devnity/domain/introduction/dto/request/SearchIntroductionRequest.java
- src/main/java/com/devnity/devnity/domain/introduction/dto/response/UserIntroductionResponse.java
- src/main/java/com/devnity/devnity/domain/introduction/entity/Introduction.java
- src/main/java/com/devnity/devnity/domain/introduction/respository/IntroductionCommentRepository.java
- src/main/java/com/devnity/devnity/domain/introduction/respository/IntroductionCustomRepository.java
- src/main/java/com/devnity/devnity/domain/introduction/respository/IntroductionCustomRepositoryImpl.java
- src/main/java/com/devnity/devnity/domain/introduction/respository/IntroductionLikeRepository.java
- src/main/java/com/devnity/devnity/domain/introduction/service/IntroductionCommentService.java
- src/main/java/com/devnity/devnity/domain/introduction/service/IntroductionLikeService.java
- src/main/java/com/devnity/devnity/domain/introduction/service/IntroductionService.java
- src/main/java/com/devnity/devnity/domain/user/controller/UserController.java
- src/main/java/com/devnity/devnity/domain/user/dto/request/SaveIntroductionRequest.java
- src/main/java/com/devnity/devnity/domain/user/dto/response/MyInfoResponse.java
- src/main/java/com/devnity/devnity/domain/user/service/UserRetrieveService.java
- src/main/java/com/devnity/devnity/domain/user/service/UserService.java
- src/test/java/com/devnity/devnity/domain/introduction/controller/IntroductionControllerTest.java
- src/test/java/com/devnity/devnity/domain/introduction/respository/IntroductionRepositoryTest.java
- src/test/java/com/devnity/devnity/domain/introduction/service/IntroductionServiceTest.java
- src/test/java/com/devnity/devnity/domain/user/controller/UserControllerTest.java
- src/test/java/com/devnity/devnity/domain/user/service/UserRetrieveServiceTest.java
- src/test/java/com/devnity/devnity/domain/user/service/UserServiceTest.java
- closes: #109 #110 
<br>
데둥이 소개 페이징 조회 기능 구현
<br>
<br>
<br>
4H
<br>
> [User-109] 데둥이 소개 페이징 조회

- src/main/java/com/devnity/devnity/domain/mapgakco/Todo.txt
- src/main/java/com/devnity/devnity/domain/mapgakco/controller/MapgakcoCommnetController.java
- src/main/java/com/devnity/devnity/domain/mapgakco/entity/MapgakcoComment.java
- src/main/java/com/devnity/devnity/domain/mapgakco/service/mapgakcocomment/MapgakcoCommentService.java
- src/test/java/com/devnity/devnity/domain/mapgakco/controller/MapgakcoCommnetControllerTest.java
- #78 
<br>
맵각코 댓글 삭제 API 구현
Test코드 작성
<br>
<br>
<br>
20m
<br>
> [Mapgakco-78] 맵각코 댓글 삭제 API 구현

- src/main/java/com/devnity/devnity/domain/mapgakco/controller/MapgakcoCommnetController.java
- src/main/java/com/devnity/devnity/domain/mapgakco/dto/mapgakcocomment/request/MapgakcoCommentUpdateRequest.java
- src/main/java/com/devnity/devnity/domain/mapgakco/service/mapgakcocomment/MapgakcoCommentService.java
- src/test/java/com/devnity/devnity/domain/mapgakco/controller/MapgakcoCommnetControllerTest.java
- #77 
<br>
댓글 수정 API 구현
댓글 수정 API Test 코드 작성
<br>
<br>
<br>
20m
<br>
> [Mapgakco-77] 댓글 수정 API 구현

- src/main/java/com/devnity/devnity/domain/gather/entity/Gather.java
- src/main/java/com/devnity/devnity/domain/gather/repository/GatherApplicantRepository.java
- src/main/java/com/devnity/devnity/domain/gather/repository/GatherRepository.java
- src/main/java/com/devnity/devnity/domain/gather/service/GatherRetrieveService.java
- #125 
<br>
제목이 곧 내용
<br>
- Gather에서 `@OneToMany`로 댓글과 신청 엔티티를 가져올때 `@OrderBy`를 사용해 정렬되게 함
<br>
- @seung-hun-h `GatherRetrieveService`에서 가져다 쓰시면됩니다~~
<br>
- 0.5h
<br>
> [Gather-125] 내가 등록/신청한 모집 조회 추가 (GatherRetrieveService)

- src/main/java/com/devnity/devnity/domain/mapgakco/converter/MapgakcoConverter.java
- src/main/java/com/devnity/devnity/domain/mapgakco/dto/SimpleMapgakcoInfoDto.java
- src/main/java/com/devnity/devnity/domain/mapgakco/dto/mapgakco/request/MapgakcoCreateRequest.java
- src/main/java/com/devnity/devnity/domain/mapgakco/entity/Mapgakco.java
- src/main/java/com/devnity/devnity/domain/mapgakco/service/MapgakcoRetrieveService.java
- src/test/java/com/devnity/devnity/domain/mapgakco/service/mapgakcoapplicant/MapgakcoApplicantServiceTest.java
- #128
<br>
MapgakcoSimpleInfoDto 관련 코드 추가
<br>
맵각코의 applicantNumber -> applicantCount로 변경
<br>
<br>
<br>
> [Mapgakco-128] 내가 등록/신청한 맵각코 조회 추가

- src/main/java/com/devnity/devnity/common/api/CursorPageRequest.java
- src/main/java/com/devnity/devnity/common/error/GlobalExceptionHandler.java
- src/main/java/com/devnity/devnity/domain/introduction/controller/IntroductionController.java
- src/main/java/com/devnity/devnity/domain/introduction/respository/custom/IntroductionCustomRepositoryImpl.java
> [User - 111] 리팩토링

- src/docs/asciidoc/domain/gathers.adoc
- src/main/java/com/devnity/devnity/common/api/ApiResponse.java
- src/main/java/com/devnity/devnity/common/error/exception/ErrorCode.java
- src/main/java/com/devnity/devnity/domain/gather/controller/GatherController.java
- src/main/java/com/devnity/devnity/domain/gather/dto/request/CreateGatherRequest.java
- src/main/java/com/devnity/devnity/domain/gather/dto/request/UpdateGatherRequest.java
- src/main/java/com/devnity/devnity/domain/gather/dto/response/GatherStatusResponse.java
- src/main/java/com/devnity/devnity/domain/gather/entity/Gather.java
- src/main/java/com/devnity/devnity/domain/gather/service/GatherApplicantService.java
- src/main/java/com/devnity/devnity/domain/gather/service/GatherService.java
- src/test/java/com/devnity/devnity/domain/gather/controller/GatherControllerTest.java
- src/test/java/com/devnity/devnity/setting/provider/GatherProvider.java
- #105 
- #106 
<br>
원래 이슈를 두개로 쪼갰었는데, 시간이 촉박해서 한 PR로 날립니다.
<br>
- 객체의 책임이 어디까지일지 정말 어렵네요. 객체지향의 길은 멀다~~~
- 모집 게시물 상태에 따른 마감 정책이 모호해서 일단 구현부터 했습니다. 빨리 정책을 세웁시다!!
- 거의 절대로 일어나지 않을 Edge case를 계속 생각하게 되는데.... 이렇게 하면 예외처리가 정말 끝도 없는것 같아요
<br>
- `LocalDateTime`의 직렬화/역직렬화 시 아래와 같이 통일해야 합니다. (프론트와도 통일)
```java
@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss", timezone = "Asia/Seoul")
```
<br>
3h
<br>
> [Gather-105] 모집 게시글 수정/삭제 API 구현

- src/main/java/com/devnity/devnity/domain/gather/repository/GatherCustomRepository.java
- src/main/java/com/devnity/devnity/domain/gather/repository/GatherCustomRepositoryImpl.java
- src/main/java/com/devnity/devnity/domain/gather/service/GatherRetrieveService.java
- src/main/java/com/devnity/devnity/domain/introduction/controller/IntroductionController.java
- src/main/java/com/devnity/devnity/domain/introduction/entity/Introduction.java
- src/main/java/com/devnity/devnity/domain/introduction/service/IntroductionService.java
- src/main/java/com/devnity/devnity/domain/introduction/service/IntroductionServiceUtils.java
- src/main/java/com/devnity/devnity/domain/mapgakco/converter/MapgakcoConverter.java
- src/main/java/com/devnity/devnity/domain/mapgakco/dto/SimpleMapgakcoInfoDto.java
- src/main/java/com/devnity/devnity/domain/mapgakco/repository/MapgakcoCustomRepository.java
- src/main/java/com/devnity/devnity/domain/mapgakco/repository/MapgakcoCustomRepositoryImpl.java
- src/main/java/com/devnity/devnity/domain/mapgakco/repository/MapgakcoRepository.java
- src/main/java/com/devnity/devnity/domain/mapgakco/service/MapgakcoRetrieveService.java
- src/main/java/com/devnity/devnity/domain/user/controller/UserController.java
- src/main/java/com/devnity/devnity/domain/user/dto/response/UserGathersResponse.java
- src/main/java/com/devnity/devnity/domain/user/entity/User.java
- src/main/java/com/devnity/devnity/domain/user/service/UserRetrieveService.java
- src/main/java/com/devnity/devnity/domain/user/service/UserService.java
- src/main/java/com/devnity/devnity/domain/user/service/UserServiceUtils.java
- src/test/java/com/devnity/devnity/domain/gather/repository/GatherCustomRepositoryTest.java
- src/test/java/com/devnity/devnity/domain/gather/service/GatherRetrieveServiceTest.java
- src/test/java/com/devnity/devnity/domain/mapgakco/repository/MapgakcoCustomRepositoryTest.java
- src/test/java/com/devnity/devnity/domain/mapgakco/service/MapgakcoRetrieveServiceTest.java
- src/test/java/com/devnity/devnity/domain/user/controller/UserControllerTest.java
- src/test/java/com/devnity/devnity/domain/user/service/IntroDto.java
- src/test/java/com/devnity/devnity/domain/user/service/TransactionTest.java
- src/test/java/com/devnity/devnity/domain/user/service/UserRetrieveServiceTest.java
- src/test/java/com/devnity/devnity/domain/user/service/UserServiceTest.java
- src/test/java/com/devnity/devnity/setting/config/TestConfig.java
- src/test/java/com/devnity/devnity/setting/provider/UserProvider.java
- closes: #112 #113 
<br>
비슷한 기능이라 한 번에 해버렸습니다!
<br>
<br>
<br>
<br>
> [User] 내가 모집한 모임 & 신청한 모임 관리 기능 구현

- src/docs/asciidoc/domain/gathers.adoc
- src/main/java/com/devnity/devnity/common/config/WebMvcConfig.java
- src/main/java/com/devnity/devnity/common/config/security/WebSecurityConfig.java
- src/main/java/com/devnity/devnity/common/utils/HealthController.java
- src/main/java/com/devnity/devnity/domain/gather/controller/GatherCommentController.java
- src/main/java/com/devnity/devnity/domain/gather/dto/request/UpdateGatherRequest.java
- src/main/java/com/devnity/devnity/domain/gather/dto/response/DeleteGatherCommentResponse.java
- src/main/java/com/devnity/devnity/domain/gather/entity/Gather.java
- src/main/java/com/devnity/devnity/domain/gather/entity/GatherComment.java
- src/main/java/com/devnity/devnity/domain/gather/service/GatherCommentService.java
- src/main/java/com/devnity/devnity/domain/gather/service/GatherService.java
- src/main/java/com/devnity/devnity/domain/user/dto/SimpleUserInfoDto.java
- src/test/java/com/devnity/devnity/domain/gather/controller/GatherApplicantControllerTest.java
- src/test/java/com/devnity/devnity/domain/gather/controller/GatherCommentControllerTest.java
- src/test/java/com/devnity/devnity/domain/gather/controller/GatherControllerTest.java
- #107 
<br>
<br>
<br>
<br>
- 1h
<br>
> [Gather-107] 모집 게시글 댓글 삭제 API 구현

- src/main/java/com/devnity/devnity/domain/admin/controller/AdminCourseController.java
- src/main/java/com/devnity/devnity/domain/admin/service/AdminCourseService.java
- #35 
<br>
- api 문서에 따라 수정시 id를 안받도록 수정
<br>
<br>
<br>
<br>
> [Admin-35] 코스 수정 request 수정

- src/docs/asciidoc/domain/mapgakco.adoc
- src/main/java/com/devnity/devnity/domain/mapgakco/controller/MapgakcoController.java
- src/main/java/com/devnity/devnity/domain/mapgakco/dto/mapgakco/request/MapgakcoPageRequest.java
- src/main/java/com/devnity/devnity/domain/mapgakco/dto/mapgakco/response/MapgakcoPageResponse.java
- src/main/java/com/devnity/devnity/domain/mapgakco/repository/mapgakcoapplicant/MapgakcoApplicantRepositoryImpl.java
- src/main/java/com/devnity/devnity/domain/mapgakco/repository/mapgakcocomment/MapgakcoCommentRepositoryImpl.java
- src/main/java/com/devnity/devnity/domain/mapgakco/service/MapService.java
- src/main/java/com/devnity/devnity/domain/mapgakco/service/mapgakco/MapgakcoService.java
- src/test/java/com/devnity/devnity/domain/mapgakco/controller/MapgakcoControllerTest.java
- src/test/java/com/devnity/devnity/domain/mapgakco/service/MapServiceTest.java
- src/test/java/com/devnity/devnity/setting/provider/MapgakcoProvider.java
- #121 
<br>
맵각코 조회 API 구현 - 중심으로부터의 거리를 정렬기준으로 이용하여 cursor 페이징
querydsl 상수관련해서 잘 안돼서 java코드로 로직 구현했습니다.
<br>
맵각코 조회용 페이징 요청, 응답 dto추가
<br>
<br>
?
<br>
> [Mapgakco-121] 맵각코 조회 API 구현

- src/docs/asciidoc/domain/mapgakco.adoc
- src/main/java/com/devnity/devnity/common/error/exception/ErrorCode.java
- src/main/java/com/devnity/devnity/common/error/exception/InvalidValueException.java
- src/main/java/com/devnity/devnity/domain/mapgakco/Todo.txt
- src/main/java/com/devnity/devnity/domain/mapgakco/controller/MapgakcoController.java
- src/main/java/com/devnity/devnity/domain/mapgakco/dto/mapgakco/request/MapgakcoUpdateRequest.java
- src/main/java/com/devnity/devnity/domain/mapgakco/entity/Mapgakco.java
- src/main/java/com/devnity/devnity/domain/mapgakco/service/mapgakco/MapgakcoService.java
- src/main/java/com/devnity/devnity/domain/mapgakco/service/mapgakcocomment/MapgakcoCommentService.java
- src/test/java/com/devnity/devnity/domain/mapgakco/controller/MapgakcoControllerTest.java
- src/test/java/com/devnity/devnity/domain/mapgakco/service/mapgakco/MapgakcoServiceTest.java
- #126 
<br>
맵각코 수정 API 구현
<br>
<br>
<br>
30m
<br>
> [Mapgakco-126] 맵각코 수정 API 구현

- src/docs/asciidoc/domain/mapgakco.adoc
> [Mapgakco] 오타 빠른수정

- src/main/java/com/devnity/devnity/common/config/WebMvcConfig.java
- src/main/java/com/devnity/devnity/common/config/security/WebSecurityConfig.java
> [User] CORS 에러 해결

- src/docs/asciidoc/domain/mapgakco.adoc
- src/main/java/com/devnity/devnity/domain/mapgakco/dto/mapgakco/response/MapgakcoPageResponse.java
- src/main/java/com/devnity/devnity/domain/mapgakco/service/mapgakco/MapgakcoService.java
- src/test/java/com/devnity/devnity/domain/mapgakco/controller/MapgakcoCommentControllerTest.java
- src/test/java/com/devnity/devnity/domain/mapgakco/controller/MapgakcoControllerTest.java
- #162 
<br>
논리오류 수정
맵각코 adoc문서 수정
<br>
<br>
<br>
1h
<br>
> [Mapgakco-162] 오류수정, 맵각코 adoc문서 내용추가

- src/docs/asciidoc/domain/mapgakco.adoc
- src/docs/asciidoc/domain/users.adoc
- src/main/java/com/devnity/devnity/domain/mapgakco/repository/mapgakcoapplicant/MapgakcoApplicantRepositoryImpl.java
- src/main/java/com/devnity/devnity/domain/mapgakco/repository/mapgakcocomment/MapgakcoCommentRepositoryImpl.java
- src/main/java/com/devnity/devnity/domain/user/controller/UserController.java
- src/main/java/com/devnity/devnity/domain/user/dto/SimpleUserMapInfoDto.java
- src/main/java/com/devnity/devnity/domain/user/dto/request/UserMapPageRequest.java
- src/main/java/com/devnity/devnity/domain/user/dto/response/UserMapPageResponse.java
- src/main/java/com/devnity/devnity/domain/user/repository/UserCustomRepository.java
- src/main/java/com/devnity/devnity/domain/user/repository/UserCustomRepositoryImpl.java
- src/main/java/com/devnity/devnity/domain/user/service/UserRetrieveService.java
- src/main/java/com/devnity/devnity/domain/user/service/UserService.java
- src/test/java/com/devnity/devnity/domain/user/controller/UserControllerTest.java
- src/test/java/com/devnity/devnity/setting/config/TestConfig.java
- src/test/java/com/devnity/devnity/setting/provider/UserProvider.java
- #160 
<br>
데둥여지도 조회 API 구현
<br>
<br>
<br>
<br>
> [User-160] 데둥여지도 조회 API 구현

- src/main/java/com/devnity/devnity/common/utils/validator/TitleValidator.java
- src/main/java/com/devnity/devnity/domain/introduction/controller/IntroductionCommentController.java
- src/main/java/com/devnity/devnity/domain/mapgakco/controller/MapgakcoController.java
- src/main/java/com/devnity/devnity/domain/mapgakco/dto/mapgakco/request/MapgakcoPageRequest.java
- src/main/resources/application-dev.yml
- src/test/java/com/devnity/devnity/domain/mapgakco/controller/MapgakcoControllerTest.java
> [Mapgakco] body를 query string으로 변경

- src/main/java/com/devnity/devnity/common/api/health/HealthController.java
- src/main/java/com/devnity/devnity/common/config/security/WebSecurityConfig.java
- src/main/java/com/devnity/devnity/common/config/security/cors/CorsConfig.java
- src/main/java/com/devnity/devnity/domain/admin/scheduler/AdminScheduler.java
- src/main/java/com/devnity/devnity/domain/gather/dto/request/CreateGatherRequest.java
- src/main/resources/application-dev.yml
- src/main/resources/application-prod.yml
- src/main/resources/application.yml
- src/test/resources/application.yml
- #171
<br>
제목이 곧 요약입니다.
<br>
이슈를 확인해주세요~~
<br>
<br>
- 30h
<br>
> [Common-171] 프로필별 CORS 허용 origin 분리

- src/docs/asciidoc/domain/mapgakco.adoc
- src/main/java/com/devnity/devnity/domain/mapgakco/controller/MapgakcoController.java
- src/main/java/com/devnity/devnity/domain/mapgakco/dto/mapgakco/request/MapgakcoRequest.java
- src/main/java/com/devnity/devnity/domain/mapgakco/service/MapService.java
- src/main/java/com/devnity/devnity/domain/mapgakco/service/MapgakcoRetrieveService.java
- src/main/java/com/devnity/devnity/domain/mapgakco/service/mapgakco/MapgakcoService.java
- src/test/java/com/devnity/devnity/domain/mapgakco/controller/MapgakcoControllerTest.java
- #170 
<br>
맵각코 조회 API V2 구현
<br>
v1코드 재사용을 위한 리펙토링 추가
<br>
<br>
1h
<br>
> [Mapgakco-170] 맵각코 조회 API V2 구현

- src/docs/asciidoc/domain/users.adoc
- src/main/java/com/devnity/devnity/domain/mapgakco/service/MapgakcoRetrieveService.java
- src/main/java/com/devnity/devnity/domain/mapgakco/service/mapgakco/MapgakcoService.java
- src/main/java/com/devnity/devnity/domain/user/controller/UserController.java
- src/main/java/com/devnity/devnity/domain/user/dto/request/UserMapPageRequest.java
- src/main/java/com/devnity/devnity/domain/user/dto/request/UserMapRequest.java
- src/main/java/com/devnity/devnity/domain/user/dto/response/UserMapPageResponse.java
- src/main/java/com/devnity/devnity/domain/user/service/UserRetrieveService.java
- src/main/java/com/devnity/devnity/domain/user/service/UserService.java
- src/test/java/com/devnity/devnity/domain/mapgakco/controller/MapgakcoControllerTest.java
- src/test/java/com/devnity/devnity/domain/user/controller/UserControllerTest.java
- #174 
<br>
데둥여지도 조회 추가 API 작성, 오류코드 수정
<br>
기존의 데둥여지도 조회 코드 재사용을 위해 리펙토링
@RequestBody -> @ModelAttribute 로 수정
<br>
<br>
40m
<br>
> [User-174] 데둥여지도 조회 추가 API 작성, 오류코드 수정

- src/main/java/com/devnity/devnity/common/error/exception/ErrorCode.java
- src/main/java/com/devnity/devnity/domain/mapgakco/controller/MapgakcoCommentController.java
- src/main/java/com/devnity/devnity/domain/mapgakco/controller/MapgakcoController.java
- src/main/java/com/devnity/devnity/domain/mapgakco/converter/MapgakcoCommentConverter.java
- src/main/java/com/devnity/devnity/domain/mapgakco/entity/MapgakcoStatus.java
- src/main/java/com/devnity/devnity/domain/mapgakco/service/mapgakco/MapgakcoService.java
- src/main/java/com/devnity/devnity/domain/mapgakco/service/mapgakcoapplicant/MapgakcoApplicantService.java
- src/main/java/com/devnity/devnity/domain/mapgakco/service/mapgakcocomment/MapgakcoCommentService.java
- src/test/java/com/devnity/devnity/domain/mapgakco/controller/MapgakcoApplicantControllerTest.java
- src/test/java/com/devnity/devnity/domain/mapgakco/controller/MapgakcoCommentControllerTest.java
- src/test/java/com/devnity/devnity/domain/mapgakco/controller/MapgakcoControllerTest.java
- src/test/java/com/devnity/devnity/domain/mapgakco/service/mapgakco/MapgakcoServiceTest.java
- src/test/java/com/devnity/devnity/domain/mapgakco/service/mapgakcoapplicant/MapgakcoApplicantServiceTest.java
- #178 
<br>
<br>
삭제/수정 API 예외처리, 신청취소 예외처리
<br>
<br>
1h
<br>
> [Mapgakco-178] 삭제/수정 API 예외처리, 신청취소 예외처리

- src/docs/asciidoc/domain/mapgakco.adoc
- src/docs/asciidoc/domain/users.adoc
- src/main/java/com/devnity/devnity/domain/mapgakco/service/MapService.java
- src/main/java/com/devnity/devnity/domain/mapgakco/service/MapgakcoRetrieveService.java
- src/main/java/com/devnity/devnity/domain/mapgakco/service/mapgakco/MapgakcoService.java
- src/main/java/com/devnity/devnity/domain/user/service/UserRetrieveService.java
- src/main/java/com/devnity/devnity/domain/user/service/UserService.java
- src/test/java/com/devnity/devnity/domain/mapgakco/controller/MapgakcoControllerTest.java
- src/test/java/com/devnity/devnity/domain/mapgakco/service/mapgakco/MapgakcoServiceTest.java
- src/test/java/com/devnity/devnity/domain/user/controller/UserControllerTest.java
- #157 
<br>
x-> longitude
y-> latitude
로 변경
<br>
<br>
<br>
30m
<br>
> [Mapgakco-157] x,y 위경도 변경

- .github/workflows/deploy-dev.yml
- .github/workflows/deploy-prod.yml
- build.gradle
- deploy/dev/deploy.sh
- deploy/prod/deploy.sh
- src/main/java/com/devnity/devnity/common/config/security/WebSecurityConfig.java
- src/main/java/com/devnity/devnity/common/utils/annotation/ApplicantLimit.java
- src/main/java/com/devnity/devnity/common/utils/validator/ApplicantLimitValidator.java
- src/main/java/com/devnity/devnity/domain/gather/dto/request/CreateGatherRequest.java
- src/main/java/com/devnity/devnity/domain/gather/event/CreateGatherApplicantEvent.java
- src/main/java/com/devnity/devnity/domain/gather/event/CreateGatherCommentEvent.java
- src/main/java/com/devnity/devnity/domain/gather/event/CreateGatherEvent.java
- src/main/java/com/devnity/devnity/domain/gather/event/DeleteGatherApplicationEvent.java
- src/main/java/com/devnity/devnity/domain/gather/event/DeleteGatherCommentEvent.java
- src/main/java/com/devnity/devnity/domain/gather/event/GatherEventHandler.java
- src/main/java/com/devnity/devnity/domain/gather/event/SimpleGatherEvent.java
- src/main/java/com/devnity/devnity/domain/gather/service/GatherService.java
- src/main/java/com/devnity/devnity/domain/gather/service/GatherUtilService.java
- src/main/resources/application-prod.yml
- src/main/resources/application.yml
- src/test/resources/application.yml
- #171
- #155 
<br>
제목이 곧 요약입니다.
<br>
<br>
<br>
<br>
> [Gather-171] CORS 허용 origin 분리 + 모집 등록시 Slack 알람 기능 구현

- src/main/java/com/devnity/devnity/domain/introduction/respository/custom/IntroductionCommentCustomRepositoryImpl.java
> [User] 서브 댓글 정렬 변경

- src/main/java/com/devnity/devnity/domain/mapgakco/controller/MapgakcoController.java
- src/main/java/com/devnity/devnity/domain/mapgakco/dto/mapgakco/response/MapgakcoCreateResponse.java
- src/main/java/com/devnity/devnity/domain/mapgakco/entity/Mapgakco.java
- src/main/java/com/devnity/devnity/domain/mapgakco/repository/mapgakcocomment/MapgakcoCommentRepositoryImpl.java
- src/main/java/com/devnity/devnity/domain/mapgakco/service/mapgakco/MapgakcoService.java
- src/main/java/com/devnity/devnity/domain/mapgakco/service/mapgakcocomment/MapgakcoCommentService.java
- src/main/java/com/devnity/devnity/domain/user/controller/UserController.java
- src/main/java/com/devnity/devnity/domain/user/dto/request/UserMapPageRequest.java
- src/main/java/com/devnity/devnity/domain/user/dto/request/UserMapRequest.java
- src/main/java/com/devnity/devnity/domain/user/repository/UserCustomRepository.java
- src/main/java/com/devnity/devnity/domain/user/repository/UserCustomRepositoryImpl.java
- src/main/java/com/devnity/devnity/domain/user/service/UserRetrieveService.java
- src/main/java/com/devnity/devnity/domain/user/service/UserService.java
- src/test/java/com/devnity/devnity/domain/mapgakco/controller/MapgakcoControllerTest.java
- src/test/java/com/devnity/devnity/domain/mapgakco/service/mapgakcoapplicant/MapgakcoApplicantServiceTest.java
- src/test/java/com/devnity/devnity/domain/user/controller/UserControllerTest.java
- #158 
<br>
데둥여지도 API 수정 등등
<br>
<br>
<br>
<br>
> [User-158] 

- src/main/java/com/devnity/devnity/domain/mapgakco/service/MapgakcoRetrieveService.java
- src/main/java/com/devnity/devnity/domain/user/dto/request/UserMapPageRequest.java
- src/main/java/com/devnity/devnity/domain/user/dto/request/UserMapRequest.java
- src/main/java/com/devnity/devnity/domain/user/repository/UserCustomRepository.java
- src/main/java/com/devnity/devnity/domain/user/repository/UserCustomRepositoryImpl.java
- src/main/java/com/devnity/devnity/domain/user/service/UserRetrieveService.java
- src/main/java/com/devnity/devnity/domain/user/service/UserService.java
- src/test/java/com/devnity/devnity/domain/user/controller/UserControllerTest.java
- #187 
<br>
데둥여지도 조회 API 이름 필터 추가
<br>
맵각코 조회 정렬 삭제함
<br>
<br>
<br>
> [User-187]   데둥여지도 조회 API 이름 필터 추가

- src/main/java/com/devnity/devnity/domain/mapgakco/controller/MapgakcoController.java
- src/main/java/com/devnity/devnity/domain/mapgakco/dto/mapgakco/request/MapgakcoCreateRequest.java
- src/main/java/com/devnity/devnity/domain/mapgakco/dto/mapgakco/request/MapgakcoPageRequest.java
- src/main/java/com/devnity/devnity/domain/mapgakco/dto/mapgakco/request/MapgakcoRequest.java
- src/main/java/com/devnity/devnity/domain/mapgakco/dto/mapgakco/request/MapgakcoUpdateRequest.java
- src/main/java/com/devnity/devnity/domain/mapgakco/dto/mapgakcocomment/request/MapgakcoCommentCreateRequest.java
- src/main/java/com/devnity/devnity/domain/mapgakco/dto/mapgakcocomment/request/MapgakcoCommentUpdateRequest.java
- src/main/java/com/devnity/devnity/domain/mapgakco/service/MapgakcoRetrieveService.java
- src/main/java/com/devnity/devnity/domain/user/dto/request/UserMapPageRequest.java
- src/main/java/com/devnity/devnity/domain/user/dto/request/UserMapRequest.java
- src/main/java/com/devnity/devnity/domain/user/repository/UserCustomRepository.java
- src/main/java/com/devnity/devnity/domain/user/repository/UserCustomRepositoryImpl.java
- src/main/java/com/devnity/devnity/domain/user/service/UserRetrieveService.java
- src/main/java/com/devnity/devnity/domain/user/service/UserService.java
- src/test/java/com/devnity/devnity/domain/user/controller/UserControllerTest.java
이미 닫힌 이슈번호, 브랜치로 잘못 수정했어요
- #187 
<br>
맵각코 validator추가
<br>
<br>
<br>
<br>
> [User-187] 맵각코 validator추가

- src/main/java/com/devnity/devnity/domain/gather/controller/GatherCommentController.java
- src/main/java/com/devnity/devnity/domain/gather/controller/GatherController.java
- src/main/java/com/devnity/devnity/domain/gather/dto/request/CreateGatherRequest.java
- src/main/java/com/devnity/devnity/domain/introduction/respository/custom/IntroductionCustomRepositoryImpl.java
- 삭제된 유저의 자기소개 읽기 버그 수정
- 마감기한 validation 수정
> [Release] v1.0.0 Beta bug fix
